app:
  tls:
    rootCAFile: /var/run/secrets/istio-csr/ca.pem

podLabels:
  tags.datadoghq.com/service: cert-manager-istio-csr

volumes:
  - name: root-ca
    secret:
      secretName: istio-root-ca

volumeMounts:
  - name: root-ca
    mountPath: /var/run/secrets/istio-csr
