app:
  server:
    clusterID: "plt-us-east1-sb"

  # tls:
  #   rootCAFile: /var/run/secrets/istio-csr/ca.pem

replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-istio-csr

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 32Mi

# volumes:
#  - name: root-ca
#    secret:
#      secretName: istio-root-ca

# volumeMounts:
#  - name: root-ca
#    mountPath: /var/run/secrets/istio-csr
